### ISSUE TITLE
Stop copying me

### ISSUE THREAD

**Issue by adamlui** [mefengl/chat-octopus#1]
Seriously...

- first you steal code
- then you notice adamlui/userscripts gains stars every day, so you copy & make chatgpt-playground for all your scripts
- then you notice I break them out into separate repo's now, so you start copying that
- then you stop with your Chinese README's and use the exact same format as me! (do not lie, your README's were all Chinese before)
- then you copy my awesome-userscripts w/ 1k+ stars by making awesome-waitlist w/ 1 star

Feng, you must stop stalking me. I blocked you for a reason, just do your own original thing! Why are you doing this? Why would you copy someone who made you angry? Just go back to writing Chinese README's (don't be blind that's where you have most success, don't blindly copy if it's not optimal)

**Comment by adamlui** [comment]
I made a big mistake in this life. I accidentally clicked edit on what of your README's, which for-created a fork. From that moment on, you became my follower but to copy is not a good reason. Inspiration is OK, but you are literally doing the exact same things. I really regret your existence, it's like Chinese piracy malware has infected my GitHub

**Comment by bigplayer-ai** [comment]
Can you add a hotkey to activate chat-octopus?
1) Press special key (SHIFT for example) + Enter for sending to multiple sites.
2) No special key pressed only the website the message was written will be sent.

**Comment by mefengl** [comment]
So much fun that you pretend you're a judge when you're not.

I don't want to reply you a lot, but I want to list the facts, there is no javascript code in the awesome-waitlist at all, in fact, this is what most of the `awesome-` prefixes go back to. I didn't even know you reopened the project to get around the MIT license.

As for the README you mentioned, you can try to ask chatgpt like this: "Write a README for the above code", if chatgpt copied your README style, please explain it to OpenAI.

By the way, all your reports in greasyfork have been rejected, and github I believe the same.

It's hard to falsely accuse innocent people, isn't it?

By the way, I might get back to you when I have time, maybe never (depending on how ridiculous your words are)

Let me mention again, awesome-waitlist doesn't have a single line of javascript code, and then it, even the README is basically generated by chatgpt based on my links, how funny, thank you for another joke

**Comment by mefengl** [comment]
> By the way, I might get back to you when I have time, maybe never (depending on how ridiculous your words are)

Sorry, I should have ended with this paragraph

**Comment by mefengl** [comment]
I shouldn't have replied,

I think I even underestimated the absurdity of your words (how I didn't learn my lesson), you mentioned awesome-userscripts with 1k+ stars, but there is only chatgpt-userscripts with 3 stars

stop making yourself a joke

**Comment by mefengl** [comment]
Maybe you live in a parallel universe, that's why I should ignore your words until Marvel's Doctor Fantastic fixes it

> By the way, I might get back to you when I have time, maybe never (depending on how ridiculous your words are)
